#!/bin/bash
#IRRecord shell script 
#This script stops lirc, and then starts irrecord and waits for one input from an ir remote.

sudo /etc/init.d/lirc stop

echo -ne "/r\nKEY_UP\n/r" > /home/pi/lirc_web/node_modules/lirc_node/irrecord/input.txt

sleep 2

sudo irrecord -d /dev/lirc0 /home/pi/lircd.conf < /home/pi/lirc_web/node_modules/lirc_node/irrecord/input.txt 

sleep 2

